/*
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.eclipse.xtext.xbase.testlanguages.contentAssistFragmentTestLang.ContentAssistFragmentTestLanguageRoot
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(ContentAssistFragmentTestLangInjectorProvider)
class ContentAssistFragmentTestLangParsingTest{

	@Inject
	ParseHelper<ContentAssistFragmentTestLanguageRoot> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
