/**
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.serializer;

import org.eclipse.xtext.xbase.testlanguages.serializer.AbstractContentAssistFragmentTestLangSemanticSequencer;

@SuppressWarnings("all")
public class ContentAssistFragmentTestLangSemanticSequencer extends AbstractContentAssistFragmentTestLangSemanticSequencer {
}
