/**
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.serializer;

import org.eclipse.xtext.xbase.testlanguages.serializer.AbstractContentAssistFragmentTestLangSyntacticSequencer;

@SuppressWarnings("all")
public class ContentAssistFragmentTestLangSyntacticSequencer extends AbstractContentAssistFragmentTestLangSyntacticSequencer {
}
