/**
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.serializer;

import org.eclipse.xtext.xbase.testlanguages.serializer.AbstractXImportSectionTestLangSyntacticSequencer;

@SuppressWarnings("all")
public class XImportSectionTestLangSyntacticSequencer extends AbstractXImportSectionTestLangSyntacticSequencer {
}
