/**
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.serializer;

import org.eclipse.xtext.xbase.testlanguages.serializer.AbstractXImportSectionTestLangSemanticSequencer;

@SuppressWarnings("all")
public class XImportSectionTestLangSemanticSequencer extends AbstractXImportSectionTestLangSemanticSequencer {
}
