/**
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.bug462047.ide;

import org.eclipse.xtext.xbase.testlanguages.bug462047.ide.AbstractBug462047LangIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class Bug462047LangIdeModule extends AbstractBug462047LangIdeModule {
}
