/**
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.bug462047.ide;

import com.google.inject.Injector;
import org.eclipse.xtext.xbase.testlanguages.bug462047.Bug462047LangStandaloneSetup;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class Bug462047LangIdeSetup extends Bug462047LangStandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from Bug462047LangIdeModule to Module");
  }
}
