/**
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.testlanguages.tests.XImportSectionTestLangInjectorProvider;
import org.eclipse.xtext.xbase.testlanguages.xImportSectionTestLang.ImportSectionTestLanguageRoot;

/* @RunWith(XtextRunner.class) */@InjectWith(XImportSectionTestLangInjectorProvider.class)
@SuppressWarnings("all")
public class XImportSectionTestLangParsingTest {
  @Inject
  private ParseHelper<ImportSectionTestLanguageRoot> parseHelper;
  
  /* @Test
   */public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field Assert is undefined"
      + "\nassertNotNull cannot be resolved");
  }
}
