/*
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.bug462047.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.eclipse.xtext.xbase.testlanguages.bug462047.bug462047.Bug462047Root
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(Bug462047LangInjectorProvider)
class Bug462047LangParsingTest{

	@Inject
	ParseHelper<Bug462047Root> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
