/*
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.bug462047.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractBug462047LangScopeProvider extends XbaseBatchScopeProvider {
}
