/**
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.scoping;

import org.eclipse.xtext.xbase.testlanguages.scoping.AbstractXImportSectionTestLangScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class XImportSectionTestLangScopeProvider extends AbstractXImportSectionTestLangScopeProvider {
}
