/*
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.ide


/**
 * Use this class to register ide components.
 */
class ContentAssistFragmentTestLangIdeModule extends AbstractContentAssistFragmentTestLangIdeModule {
}
