/*
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.ide

import com.google.inject.Guice
import org.eclipse.xtext.xbase.testlanguages.ContentAssistFragmentTestLangRuntimeModule
import org.eclipse.xtext.xbase.testlanguages.ContentAssistFragmentTestLangStandaloneSetup

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ContentAssistFragmentTestLangIdeSetup extends ContentAssistFragmentTestLangStandaloneSetup {

	override createInjector() {
		Guice.createInjector(new ContentAssistFragmentTestLangRuntimeModule, new ContentAssistFragmentTestLangIdeModule)
	}
}
