/*
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ContentAssistFragmentTestLangRuntimeModule extends AbstractContentAssistFragmentTestLangRuntimeModule {
}
