/*
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ContentAssistFragmentTestLangStandaloneSetup extends ContentAssistFragmentTestLangStandaloneSetupGenerated {

	def static void doSetup() {
		new ContentAssistFragmentTestLangStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
