/*
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class XImportSectionTestLangStandaloneSetup extends XImportSectionTestLangStandaloneSetupGenerated {

	def static void doSetup() {
		new XImportSectionTestLangStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
