/*
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.ide;

import com.google.inject.Binder;
import com.google.inject.name.Names;
import org.eclipse.xtext.ide.DefaultIdeModule;
import org.eclipse.xtext.ide.LexerIdeBindings;
import org.eclipse.xtext.ide.editor.contentassist.antlr.IContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer;
import org.eclipse.xtext.xbase.testlanguages.ide.contentassist.antlr.XImportSectionTestLangParser;
import org.eclipse.xtext.xbase.testlanguages.ide.contentassist.antlr.internal.InternalXImportSectionTestLangLexer;

/**
 * Manual modifications go to {@link XImportSectionTestLangIdeModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractXImportSectionTestLangIdeModule extends DefaultIdeModule {

	// contributed by org.eclipse.xtext.xtext.generator.parser.antlr.XtextAntlrGeneratorFragment2
	public void configureContentAssistLexer(Binder binder) {
		binder.bind(Lexer.class)
			.annotatedWith(Names.named(LexerIdeBindings.CONTENT_ASSIST))
			.to(InternalXImportSectionTestLangLexer.class);
	}
	
	// contributed by org.eclipse.xtext.xtext.generator.parser.antlr.XtextAntlrGeneratorFragment2
	public Class<? extends IContentAssistParser> bindIContentAssistParser() {
		return XImportSectionTestLangParser.class;
	}
	
}
