/**
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.ide;

import com.google.inject.Injector;
import org.eclipse.xtext.xbase.testlanguages.ContentAssistFragmentTestLangStandaloneSetup;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ContentAssistFragmentTestLangIdeSetup extends ContentAssistFragmentTestLangStandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from ContentAssistFragmentTestLangIdeModule to Module");
  }
}
