/**
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.ide;

import org.eclipse.xtext.xbase.testlanguages.ide.AbstractContentAssistFragmentTestLangIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ContentAssistFragmentTestLangIdeModule extends AbstractContentAssistFragmentTestLangIdeModule {
}
