/**
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.ide;

import org.eclipse.xtext.xbase.testlanguages.ide.AbstractXImportSectionTestLangIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class XImportSectionTestLangIdeModule extends AbstractXImportSectionTestLangIdeModule {
}
