/*
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class ContentAssistFragmentTestLangScopeProvider extends AbstractContentAssistFragmentTestLangScopeProvider {

}
