/**
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.bug462047.serializer;

import org.eclipse.xtext.xbase.testlanguages.bug462047.serializer.AbstractBug462047LangSemanticSequencer;

@SuppressWarnings("all")
public class Bug462047LangSemanticSequencer extends AbstractBug462047LangSemanticSequencer {
}
