/**
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.bug462047.serializer;

import org.eclipse.xtext.xbase.testlanguages.bug462047.serializer.AbstractBug462047LangSyntacticSequencer;

@SuppressWarnings("all")
public class Bug462047LangSyntacticSequencer extends AbstractBug462047LangSyntacticSequencer {
}
