/*
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.bug462047.ide


/**
 * Use this class to register ide components.
 */
class Bug462047LangIdeModule extends AbstractBug462047LangIdeModule {
}
