/**
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.bug462047.scoping;

import org.eclipse.xtext.xbase.testlanguages.bug462047.scoping.AbstractBug462047LangScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class Bug462047LangScopeProvider extends AbstractBug462047LangScopeProvider {
}
