/**
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.bug462047.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.testlanguages.bug462047.bug462047.Bug462047Root;
import org.eclipse.xtext.xbase.testlanguages.bug462047.tests.Bug462047LangInjectorProvider;

/* @RunWith(XtextRunner.class) */@InjectWith(Bug462047LangInjectorProvider.class)
@SuppressWarnings("all")
public class Bug462047LangParsingTest {
  @Inject
  private ParseHelper<Bug462047Root> parseHelper;
  
  /* @Test
   */public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field Assert is undefined"
      + "\nassertNotNull cannot be resolved");
  }
}
