/**
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages;

import org.eclipse.xtext.xbase.testlanguages.AbstractContentAssistFragmentTestLangRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ContentAssistFragmentTestLangRuntimeModule extends AbstractContentAssistFragmentTestLangRuntimeModule {
}
