/**
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages;

import org.eclipse.xtext.xbase.testlanguages.ContentAssistFragmentTestLangStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ContentAssistFragmentTestLangStandaloneSetup extends ContentAssistFragmentTestLangStandaloneSetupGenerated {
  public static void doSetup() {
    new ContentAssistFragmentTestLangStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
