/**
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages;

import org.eclipse.xtext.xbase.testlanguages.XImportSectionTestLangStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class XImportSectionTestLangStandaloneSetup extends XImportSectionTestLangStandaloneSetupGenerated {
  public static void doSetup() {
    new XImportSectionTestLangStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
