/*
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.bug462047.ide;

import com.google.inject.Binder;
import com.google.inject.name.Names;
import org.eclipse.xtext.ide.DefaultIdeModule;
import org.eclipse.xtext.ide.LexerIdeBindings;
import org.eclipse.xtext.ide.editor.contentassist.antlr.IContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer;
import org.eclipse.xtext.xbase.testlanguages.bug462047.ide.contentassist.antlr.Bug462047LangParser;
import org.eclipse.xtext.xbase.testlanguages.bug462047.ide.contentassist.antlr.internal.InternalBug462047LangLexer;

/**
 * Manual modifications go to {@link Bug462047LangIdeModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractBug462047LangIdeModule extends DefaultIdeModule {

	// contributed by org.eclipse.xtext.xtext.generator.parser.antlr.XtextAntlrGeneratorFragment2
	public void configureContentAssistLexer(Binder binder) {
		binder.bind(Lexer.class)
			.annotatedWith(Names.named(LexerIdeBindings.CONTENT_ASSIST))
			.to(InternalBug462047LangLexer.class);
	}
	
	// contributed by org.eclipse.xtext.xtext.generator.parser.antlr.XtextAntlrGeneratorFragment2
	public Class<? extends IContentAssistParser> bindIContentAssistParser() {
		return Bug462047LangParser.class;
	}
	
}
