/*
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.serializer


class ContentAssistFragmentTestLangSyntacticSequencer extends AbstractContentAssistFragmentTestLangSyntacticSequencer {
}
