/**
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.bug462047;

import org.eclipse.xtext.xbase.testlanguages.bug462047.Bug462047LangStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class Bug462047LangStandaloneSetup extends Bug462047LangStandaloneSetupGenerated {
  public static void doSetup() {
    new Bug462047LangStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
