/**
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.bug462047;

import org.eclipse.xtext.xbase.testlanguages.bug462047.AbstractBug462047LangRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class Bug462047LangRuntimeModule extends AbstractBug462047LangRuntimeModule {
}
