/*
 * generated by Xtext
 */
package org.eclipse.xtext.xbase.testlanguages.bug462047


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class Bug462047LangStandaloneSetup extends Bug462047LangStandaloneSetupGenerated {

	def static void doSetup() {
		new Bug462047LangStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
